name: deploy

on:
  push:
    branches: [trunk]
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      upload_pages_artifact: ${{ github.ref == 'refs/heads/trunk' }}

  deploy:
    if: github.ref == 'refs/heads/trunk'
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
        with:
          cname: dayxday.app
